---
-  hosts: ws
   become: true
   ignore_errors: 1
   gather_facts : yes
   vars:
    package_name: httpd
   tasks:
     - name: Install package
       yum:
         name: "{{package_name}}"
         state: present

    #  - name: create groups 
    #    group:
    #     name: "{{ item }}"
    #     state: present

    #    loop:
    #        - cloud
    #        - security
    #        - devops
    #        - linuxsa
     - name: Create group
       group:
         name: "{{ items }}"
         state: present
       with_items:
           - cloud
           - security
           - devops
           - linuxas