---
- hosts: all
  become: true
  ignore_errors: 1
  gather_facts : yes
  tasks:
      - name : Create a file 
        file:
          path: /tmp/playbookfile
          mode: '0755'
          state: touch
      - name: check someting 
        command: jfdlfm
        
      - name: Create a directory
        file: 
         path: /tmp/dir
         mode: '0700'
         state: directory 
      - name: Create group
        group:
          name: security
          state: present
      - name:  Create user Delano 
        user:
          comment: Delano Noumbou
          shell: /bin/bash
          group: security 
          name: Delano
        when: ansible_os_family == "Debian" or ansible_processor_nproc > 2 
      - name: check uptime 
        command: uptime
      - name: check the date
        shell: cat /etc/passwd | grep Delano